// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wfc.referential.Infrastructure.Data;

#nullable disable

namespace wfc.referential.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("wfc.referential.Domain.AffiliateAggregate.Affiliate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AccountingAccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountingDocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AffiliateTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationDay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StampDutyMention")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("ThresholdBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AffiliateTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Affiliates", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.AgencyAggregate.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountingAccountNumber")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AccountingSheetName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Address2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AgencyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CashTransporter")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ExpenseFundAccountNumber")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ExpenseFundAccountingSheet")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("FundingThreshold")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid?>("FundingTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("MadAccount")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupportAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TokenUsageStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgencyTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FundingTypeId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SupportAccountId");

                    b.HasIndex("TokenUsageStatusId");

                    b.ToTable("Agencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agency_CityOrSector", "((\"CityId\" IS NOT NULL AND \"SectorId\" IS NULL) OR\r\n           (\"CityId\" IS NULL     AND \"SectorId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("wfc.referential.Domain.AgencyTierAggregate.AgencyTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.HasIndex("AgencyId", "TierId", "Code")
                        .IsUnique();

                    b.ToTable("AgencyTiers", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.BankAggregate.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("wfc.referential.Domain.CityAggregate.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("wfc.referential.Domain.ContractAggregate.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.ContractDetailsAggregate.ContractDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PricingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PricingId");

                    b.HasIndex("ContractId", "PricingId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContractDetails_ContractId_PricingId");

                    b.ToTable("ContractDetails", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.ControleAggregate.Controle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Controles", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.CorridorAggregate.Corridor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DestinationBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationCountryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCountryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationBranchId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("DestinationCountryId");

                    b.HasIndex("SourceBranchId");

                    b.HasIndex("SourceCityId");

                    b.HasIndex("SourceCountryId");

                    b.ToTable("Corridors");
                });

            modelBuilder.Entity("wfc.referential.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("DialingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSector")
                        .HasColumnType("boolean");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<string>("ISO3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSmsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("MonetaryZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberDecimalDigits")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.HasIndex("MonetaryZoneId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("wfc.referential.Domain.CountryIdentityDocAggregate.CountryIdentityDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityDocumentId");

                    b.HasIndex("CountryId", "IdentityDocumentId")
                        .IsUnique();

                    b.ToTable("CountryIdentityDocs");
                });

            modelBuilder.Entity("wfc.referential.Domain.CountryServiceAggregate.CountryService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CountryId", "ServiceId")
                        .IsUnique();

                    b.ToTable("CountryServices");
                });

            modelBuilder.Entity("wfc.referential.Domain.CurrencyAggregate.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeAR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodeIso")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CodeIso")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("wfc.referential.Domain.IdentityDocumentAggregate.IdentityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IdentityDocuments");
                });

            modelBuilder.Entity("wfc.referential.Domain.MonetaryZoneAggregate.MonetaryZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MonetaryZones");
                });

            modelBuilder.Entity("wfc.referential.Domain.ParamTypeAggregate.ParamType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TypeDefinitionId");

                    b.ToTable("ParamTypes");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerAccountAggregate.PartnerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Domiciliation")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("RIB")
                        .IsUnique();

                    b.ToTable("PartnerAccounts");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerAggregate.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthenticationMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuxiliaryAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CommissionAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunctionContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadquartersAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadquartersCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdParent")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NetworkModeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartnerTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentModeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalTaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupportAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupportAccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxRegime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WithholdingTaxRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ICE")
                        .IsUnique();

                    b.HasIndex("NetworkModeId");

                    b.HasIndex("PartnerTypeId");

                    b.HasIndex("PaymentModeId");

                    b.HasIndex("SupportAccountTypeId");

                    b.HasIndex("TaxIdentificationNumber")
                        .IsUnique();

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerCountryAggregate.PartnerCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("PartnerId", "CountryId")
                        .IsUnique();

                    b.ToTable("PartnerCountries", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.PricingAggregate.Pricing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffiliateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("FixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CorridorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Pricings", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("wfc.referential.Domain.RegionAggregate.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("wfc.referential.Domain.SectorAggregate.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("wfc.referential.Domain.ServiceAggregate.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("wfc.referential.Domain.ServiceControleAggregate.ServiceControle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ControleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("ExecOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ControleId");

                    b.HasIndex("ServiceId", "ControleId", "ChannelId")
                        .IsUnique();

                    b.ToTable("ServiceControles", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.SupportAccountAggregate.SupportAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AccountingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupportAccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountingNumber")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("SupportAccountTypeId");

                    b.ToTable("SupportAccounts");
                });

            modelBuilder.Entity("wfc.referential.Domain.TaxAggregate.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodeAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<double?>("FixedAmount")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Rate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("wfc.referential.Domain.TaxRuleDetailAggregate.TaxRuleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AppliedOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorridorId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TaxId");

                    b.ToTable("TaxRuleDetails");
                });

            modelBuilder.Entity("wfc.referential.Domain.TierAggregate.Tier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tiers", (string)null);
                });

            modelBuilder.Entity("wfc.referential.Domain.TypeDefinitionAggregate.TypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeDefinitions");
                });

            modelBuilder.Entity("wfc.referential.Domain.AffiliateAggregate.Affiliate", b =>
                {
                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "AffiliateType")
                        .WithMany()
                        .HasForeignKey("AffiliateTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AffiliateType");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("wfc.referential.Domain.AgencyAggregate.Agency", b =>
                {
                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "AgencyType")
                        .WithMany()
                        .HasForeignKey("AgencyTypeId");

                    b.HasOne("wfc.referential.Domain.CityAggregate.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "FundingType")
                        .WithMany()
                        .HasForeignKey("FundingTypeId");

                    b.HasOne("wfc.referential.Domain.PartnerAggregate.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.HasOne("wfc.referential.Domain.SectorAggregate.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId");

                    b.HasOne("wfc.referential.Domain.SupportAccountAggregate.SupportAccount", "SupportAccount")
                        .WithMany()
                        .HasForeignKey("SupportAccountId");

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "TokenUsageStatus")
                        .WithMany()
                        .HasForeignKey("TokenUsageStatusId");

                    b.Navigation("AgencyType");

                    b.Navigation("City");

                    b.Navigation("FundingType");

                    b.Navigation("Partner");

                    b.Navigation("Sector");

                    b.Navigation("SupportAccount");

                    b.Navigation("TokenUsageStatus");
                });

            modelBuilder.Entity("wfc.referential.Domain.AgencyTierAggregate.AgencyTier", b =>
                {
                    b.HasOne("wfc.referential.Domain.AgencyAggregate.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.TierAggregate.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("wfc.referential.Domain.CityAggregate.City", b =>
                {
                    b.HasOne("wfc.referential.Domain.RegionAggregate.Region", null)
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("wfc.referential.Domain.ContractAggregate.Contract", b =>
                {
                    b.HasOne("wfc.referential.Domain.PartnerAggregate.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("wfc.referential.Domain.ContractDetailsAggregate.ContractDetails", b =>
                {
                    b.HasOne("wfc.referential.Domain.ContractAggregate.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.PricingAggregate.Pricing", "Pricing")
                        .WithMany()
                        .HasForeignKey("PricingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Pricing");
                });

            modelBuilder.Entity("wfc.referential.Domain.CorridorAggregate.Corridor", b =>
                {
                    b.HasOne("wfc.referential.Domain.AgencyAggregate.Agency", "DestinationBranch")
                        .WithMany()
                        .HasForeignKey("DestinationBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.CityAggregate.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.Countries.Country", "DestinationCountry")
                        .WithMany()
                        .HasForeignKey("DestinationCountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.AgencyAggregate.Agency", "SourceBranch")
                        .WithMany()
                        .HasForeignKey("SourceBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.CityAggregate.City", "SourceCity")
                        .WithMany()
                        .HasForeignKey("SourceCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.Countries.Country", "SourceCountry")
                        .WithMany()
                        .HasForeignKey("SourceCountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationBranch");

                    b.Navigation("DestinationCity");

                    b.Navigation("DestinationCountry");

                    b.Navigation("SourceBranch");

                    b.Navigation("SourceCity");

                    b.Navigation("SourceCountry");
                });

            modelBuilder.Entity("wfc.referential.Domain.Countries.Country", b =>
                {
                    b.HasOne("wfc.referential.Domain.CurrencyAggregate.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.MonetaryZoneAggregate.MonetaryZone", null)
                        .WithMany("Countries")
                        .HasForeignKey("MonetaryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("wfc.referential.Domain.CountryIdentityDocAggregate.CountryIdentityDoc", b =>
                {
                    b.HasOne("wfc.referential.Domain.Countries.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.IdentityDocumentAggregate.IdentityDocument", null)
                        .WithMany()
                        .HasForeignKey("IdentityDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wfc.referential.Domain.CountryServiceAggregate.CountryService", b =>
                {
                    b.HasOne("wfc.referential.Domain.Countries.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.ServiceAggregate.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wfc.referential.Domain.ParamTypeAggregate.ParamType", b =>
                {
                    b.HasOne("wfc.referential.Domain.TypeDefinitionAggregate.TypeDefinition", "TypeDefinition")
                        .WithMany("ParamTypes")
                        .HasForeignKey("TypeDefinitionId")
                        .IsRequired();

                    b.Navigation("TypeDefinition");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerAccountAggregate.PartnerAccount", b =>
                {
                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.BankAggregate.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerAggregate.Partner", b =>
                {
                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "NetworkMode")
                        .WithMany()
                        .HasForeignKey("NetworkModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "PartnerType")
                        .WithMany()
                        .HasForeignKey("PartnerTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "PaymentMode")
                        .WithMany()
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "SupportAccountType")
                        .WithMany()
                        .HasForeignKey("SupportAccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NetworkMode");

                    b.Navigation("PartnerType");

                    b.Navigation("PaymentMode");

                    b.Navigation("SupportAccountType");
                });

            modelBuilder.Entity("wfc.referential.Domain.PartnerCountryAggregate.PartnerCountry", b =>
                {
                    b.HasOne("wfc.referential.Domain.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.PartnerAggregate.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("wfc.referential.Domain.PricingAggregate.Pricing", b =>
                {
                    b.HasOne("wfc.referential.Domain.AffiliateAggregate.Affiliate", "Affiliate")
                        .WithMany()
                        .HasForeignKey("AffiliateId");

                    b.HasOne("wfc.referential.Domain.CorridorAggregate.Corridor", "Corridor")
                        .WithMany()
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.ServiceAggregate.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Affiliate");

                    b.Navigation("Corridor");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("wfc.referential.Domain.RegionAggregate.Region", b =>
                {
                    b.HasOne("wfc.referential.Domain.Countries.Country", null)
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wfc.referential.Domain.SectorAggregate.Sector", b =>
                {
                    b.HasOne("wfc.referential.Domain.CityAggregate.City", "City")
                        .WithMany("Sectors")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("wfc.referential.Domain.ServiceAggregate.Service", b =>
                {
                    b.HasOne("wfc.referential.Domain.ProductAggregate.Product", null)
                        .WithMany("Services")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wfc.referential.Domain.ServiceControleAggregate.ServiceControle", b =>
                {
                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.ControleAggregate.Controle", "Controle")
                        .WithMany()
                        .HasForeignKey("ControleId")
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.ServiceAggregate.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Controle");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("wfc.referential.Domain.SupportAccountAggregate.SupportAccount", b =>
                {
                    b.HasOne("wfc.referential.Domain.PartnerAggregate.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("wfc.referential.Domain.ParamTypeAggregate.ParamType", "SupportAccountType")
                        .WithMany()
                        .HasForeignKey("SupportAccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Partner");

                    b.Navigation("SupportAccountType");
                });

            modelBuilder.Entity("wfc.referential.Domain.TaxRuleDetailAggregate.TaxRuleDetail", b =>
                {
                    b.HasOne("wfc.referential.Domain.CorridorAggregate.Corridor", "Corridor")
                        .WithMany("TaxRuleDetails")
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.ServiceAggregate.Service", "Service")
                        .WithMany("TaxRuleDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wfc.referential.Domain.TaxAggregate.Tax", "Tax")
                        .WithMany("TaxRuleDetails")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corridor");

                    b.Navigation("Service");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("wfc.referential.Domain.CityAggregate.City", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("wfc.referential.Domain.CorridorAggregate.Corridor", b =>
                {
                    b.Navigation("TaxRuleDetails");
                });

            modelBuilder.Entity("wfc.referential.Domain.Countries.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("wfc.referential.Domain.CurrencyAggregate.Currency", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("wfc.referential.Domain.MonetaryZoneAggregate.MonetaryZone", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("wfc.referential.Domain.ProductAggregate.Product", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("wfc.referential.Domain.RegionAggregate.Region", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("wfc.referential.Domain.ServiceAggregate.Service", b =>
                {
                    b.Navigation("TaxRuleDetails");
                });

            modelBuilder.Entity("wfc.referential.Domain.TaxAggregate.Tax", b =>
                {
                    b.Navigation("TaxRuleDetails");
                });

            modelBuilder.Entity("wfc.referential.Domain.TypeDefinitionAggregate.TypeDefinition", b =>
                {
                    b.Navigation("ParamTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
