apiVersion: v1
kind: ConfigMap
metadata:
  name: wfc-referential-api-config
  namespace: #{k8sNamespace}#
  labels:
    app: wfc-referential-api
    version: v1
data:
  appsettings.json: |
    {
      "Kestrel": {
            "Endpoints": {
              "Https": {
                "Url": "https://*:8080",  // Listen on HTTPS
                "Certificate": {
                  "Path": "/app/certs/tls.crt",
                  "KeyPath": "/app/certs/tls.key"
                }
              }
            }
      },
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning"
            }
        },
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
                }
            },
            {
                "Name": "File",
                "Args": {
                    "path": "logs/app-.log",
                    "rollingInterval": "Day",
                    "retainedFileCountLimit": 30,
                    "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
                }
            }
        ],
        "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
     },
      "AppSettings": {
        "ApiTimeout": 30,
        "MaxRetries": 3,
        "EnableFeatureX": true
      },
      "Cors": {
        "AllowedHosts": [ "#{Cors__AllowedHosts__0}#" ]
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
          "Database": "#{ConnectionStrings__wfc.referential.dbc}#",
          "Redis": "#{ConnectionStrings__wfc.referential.redis}#"
      },
     "SpecialCharacterValidation": {
          "ForbiddenCharactersPattern": "#{ForbiddenCharactersPattern__wfc.referential}#",
          "ExcludedProperties": ["password","token","signature","hash","key","secret"],
          "EnableDetailedErrorMessages": true,
          "IsEnabled": false
     }
    }