apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-referential
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/referential
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists  # Ensures only worker nodes are selected i used : kubectl label nodes poc-ks-worker1 poc-ks-worker2 node-role.kubernetes.io/worker=true
        # Optional: Explicitly exclude control-plane nodes
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist