apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wfc-referential-api-disk-pvc
  namespace: #{k8sNamespace}#
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi